provider_x_repository:
  http_client:
    timeout: 5000ms
  api_domain: https://provider.code-challenge.feverup.com
  external_calls:
    get_current_events:
      request_uri: /api/events
network_nodes_kvs:
  name: DELIVERY_FACILITIES_KVS
  read_timeout: 250ms
  write_timeout: 350ms
  max_retries: 2